use_frameworks!

platform :ios, '8.0'

target 'XYYNetWorkManager_Example' do
  pod 'XYYNetWorkManager', :path => '../'

  target 'XYYNetWorkManager_Tests' do
    inherit! :search_paths

    
  end
end
